platform: linux

image_resource:
  type: docker-image
  source:
    repository: jamesdbloom/docker-java8-maven
    tag: latest

inputs:
  - name: resource-git

run:
  path: resource-git/concourse/build.sh
