resources:
  - name: resource-git
    type: git
    source:
      uri: {{github-uri}}
      branch: {{github-branch}}
  - name: resource-cf
    type: cf
    source:
      api: {{cf-api}}
      username: {{cf-username}}
      password: {{cf-password}}
      organization: {{cf-org}}
      space: {{cf-space}}
      skip_cert_check: true

jobs:
  - name: package-job
    plan:
      - get: resource-git
        trigger: true
      - task: package-task
        file: resource-git/concourse/build.yml
      - put: resource-cf
        params:
          manifest: resource-git/manifest.yml
